import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import { Varela_Round } from 'next/font/google';
import "./globals.css";


const varelaRound = Varela_Round({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app ", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varelaRound.className} `}

      >
      <Navbar />
        <div className="bg-bg_light dark:bg-bg_dark px-2 sm:px-4 md:px-8">

          {children}
        </div>
      </body>
    </html>
  );
}